### ISSUE TITLE
Add ignore_dependencies to rvm_gem type?

### ISSUE THREAD

**Issue by alexjfisher** [maestrodev/puppet-rvm#116]
In my hiera, I specify the exact gem versions I want installed for a dozen or so gems.

Depending on the order they get installed, i can end up with some gems having multiple versions installed.

eg today in my hiera I have
```
my_gems:
  'unf':
    ensure: '0.1.4'
  'unf_ext':
    ensure: '0.0.7.1'
```

When unf gets installed before unf_ext, it pulls in unf_ext 0.0.7.2 (which wasn't out when I pinned to 0.0.7.1).
The Rvm_gem['unf_ext'] then installs 0.0.7.1 as asked, but I'm left with both gems installed.
an 'ignore_dependencies' parameter would be useful.  It could default to false.
If this sounds reasonable, I'll work on a PR.

Kind Regards,
Alex
